// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTuwCF0Ju-X06Q4PmwNd8bC5QaJXFDD30',
    appId: '1:332592438539:web:6ebcea6cb074f98b3fd60e',
    messagingSenderId: '332592438539',
    projectId: 'hackatonia-84d30',
    authDomain: 'hackatonia-84d30.firebaseapp.com',
    storageBucket: 'hackatonia-84d30.firebasestorage.app',
    measurementId: 'G-9C45YT6ZP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeRwCSUhg-M2J7FTN3CCD6T13Dj_GtiA8',
    appId: '1:332592438539:android:055de97ab0e3d2c13fd60e',
    messagingSenderId: '332592438539',
    projectId: 'hackatonia-84d30',
    storageBucket: 'hackatonia-84d30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM61jO2oWTACAxkssjQxaHf-Ool9Pt57g',
    appId: '1:332592438539:ios:37043d8758ec7e933fd60e',
    messagingSenderId: '332592438539',
    projectId: 'hackatonia-84d30',
    storageBucket: 'hackatonia-84d30.firebasestorage.app',
    iosBundleId: 'com.example.reinserta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM61jO2oWTACAxkssjQxaHf-Ool9Pt57g',
    appId: '1:332592438539:ios:37043d8758ec7e933fd60e',
    messagingSenderId: '332592438539',
    projectId: 'hackatonia-84d30',
    storageBucket: 'hackatonia-84d30.firebasestorage.app',
    iosBundleId: 'com.example.reinserta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTuwCF0Ju-X06Q4PmwNd8bC5QaJXFDD30',
    appId: '1:332592438539:web:d63954613edf16023fd60e',
    messagingSenderId: '332592438539',
    projectId: 'hackatonia-84d30',
    authDomain: 'hackatonia-84d30.firebaseapp.com',
    storageBucket: 'hackatonia-84d30.firebasestorage.app',
    measurementId: 'G-PKTKZBTHZ0',
  );
}
